### ISSUE TITLE
fails to build

### ISSUE THREAD

**Issue by mgmax** [t-oster/VisicutBuilder#5]
`./build.sh: line 48: pushd: /app/build/VisiCut/src/com/t_oster/visicut/gui/resources/: No such file or directory`

Strange enough, download.visicut.org works properly. Does it still use VisiCutBuilder?

**Comment by t-oster** [comment]
Sorry I published only at gitlab and did not synchronize to GitHub. Will push tomorrow, otherwise look at gitlab

**Comment by t-oster** [comment]
its synced now. I use gitlab because it automatically builds the docker image for me
